// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"exchange-api/internal/midd"
	"exchange-api/internal/svc"
)

func OrderHandlers(r *Routers, serverCtx *svc.ServiceContext) {
	// 注册路由
	orderHistoryHandler := NewOrderHistoryHandler(serverCtx)
	orderCurrentHandler := NewOrderCurrentHandler(serverCtx)
	addHandler := NewAddHandler(serverCtx)
	orderGroup := r.Group()
	// 设置中间件
	orderGroup.Use(midd.Auth(serverCtx.Config.JWT.AccessSecret))
	// 历史委托查询，即所有委托
	orderGroup.Post("/exchange/order/history", orderHistoryHandler)
	// 当前的委托查询，即正在交易的状态
	orderGroup.Post("/exchange/order/current", orderCurrentHandler)
	// 新增委托
	orderGroup.Post("/exchange/order/add", addHandler)
}
