// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"market-api/internal/svc"
)

func ExchangeRateHandlers(r *Routers, serverCtx *svc.ServiceContext) {
	// 注册路由
	exchangeRateHandler := NewUsdRateHandler(serverCtx)
	exchangeRateGroup := r.Group()
	exchangeRateGroup.Post("/market/exchange-rate/usd/:unit", exchangeRateHandler)

	// 市场相关的路由
	symbolThumbTrendHandler := NewSymbolThumbTrendHandler(serverCtx)
	symbolThumbHandler := NewSymbolThumbHandler(serverCtx)
	symbolInfoHandler := NewSymbolInfoHandler(serverCtx)
	coinsymbolInfoHandler := NewCoinInfoHandler(serverCtx)
	historyHandler := NewHistoryHandler(serverCtx)

	marketGroup := r.Group()
	marketGroup.Post("/market/symbol-thumb-trend", symbolThumbTrendHandler)
	marketGroup.Post("/market/symbol-thumb", symbolThumbHandler)
	marketGroup.Post("/market/symbol-info", symbolInfoHandler)
	marketGroup.Post("/market/coin-info", coinsymbolInfoHandler)
	marketGroup.Get("/market/history", historyHandler)

	// TODO 思考为什么需要在这里设置router
	// 我的想法是router的注册周期是在项目初始化的时候，需要在router注册过才不会报404（注册但不处理）
	wsServerGroup := r.Group()
	wsServerGroup.Get("/socket.io", nil)
	wsServerGroup.Post("/socket.io", nil)
}
